require_relative 'rust-core'
require_relative 'rust-basics'
require_relative 'rust-csv'
require_relative 'rust-tests'
require_relative 'rust-effsize'
require_relative 'rust-descriptive'
require_relative 'rust-plots'
require_relative 'rust-calls'
